### ISSUE TITLE
refreshing window problem

### ISSUE THREAD

**Issue by volkov68** [clementfarabet/gfx.js#20]
hi guys,
when i'm using something like : 
_win1_=gfx.image(img1, {win=_win1_, zoom=2,legend="r"})         -- the first time it's work fine = show a window with the image

wait 2sec

_win1_=gfx.image(img2, {win=_win1_, zoom=2,legend="r"})         -- the second time it keep showing the first image (img1), but when i click the image, new tab is opened and display correctly the img2

any idea?!!
thx

**Comment by soumith** [comment]
Hey, which browser are you using?

**Comment by volkov68** [comment]
Hi Soumith,
i'm using google chrome (ubuntu 14.04)

**Comment by volkov68** [comment]
another thing when the img is a tensor with more than one dimension (ex: img=torch.Tensor(10,100,100)) there's no problem, the listener works fine.

**Comment by soumith** [comment]
a little late, but this PR fixes the issue: https://github.com/clementfarabet/gfx.js/pull/30

**Comment by volkov68** [comment]
Thanks Soumith, your'e the best.
