### ISSUE TITLE
-lgfx.go error (graphicsmagick problem)

### ISSUE THREAD

**Issue by bluekidds** [clementfarabet/gfx.js#26]
Hi:
I'm using OSX Mavericks and installed gfx.js. 
However, when I execute 'luajit -lgfx.go', it always show an error:

"luajit: /usr/local/share/lua/5.1/gfx/js.lua:9: module 'graphicsmagick' not found:
    no field package.preload['graphicsmagick']
    no file '/usr/local/share/lua/5.1/graphicsmagick.lua'
    no file '/usr/local/share/lua/5.1/graphicsmagick/init.lua'
    no file '/Users/bluekidds/.luarocks/share/lua/5.1/graphicsmagick.lua'
    no file '/Users/bluekidds/.luarocks/share/lua/5.1/graphicsmagick/init.lua'
    no file './graphicsmagick.lua'
    no file '/usr/local/share/luajit-2.0.2/graphicsmagick.lua'
    no file '/usr/local/share/lua/5.1/graphicsmagick.lua'
    no file '/usr/local/share/lua/5.1/graphicsmagick/init.lua'
    no file '/usr/local/lib/lua/5.1/graphicsmagick.so'
    no file '/Users/bluekidds/.luarocks/lib/lua/5.1/graphicsmagick.so'
    no file './graphicsmagick.so'
    no file '/usr/local/lib/lua/5.1/graphicsmagick.so'
    no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
    [C]: in function 'require'
    /usr/local/share/lua/5.1/gfx/js.lua:9: in main chunk
    [C]: in function 'require'
    /usr/local/share/lua/5.1/gfx/go.lua:7: in main chunk
    [C]: at 0x010a4a6ed0
    [C]: at 0x010a47a8b0"

I've installed several times on other OSX system but this hasn't happen before. Is there anything I could fix?

**Comment by weihua04** [comment]
did you problem have been solved? i have the same problem.
