### ISSUE TITLE
Shell Access through browser == Vulnerability ?

### ISSUE THREAD

**Issue by andi4000** [clementfarabet/gfx.js#34]
Hi,

Not sure if this is the correct forum to ask this, but with term/shell available through the browser, isn't my computer/server become vulnerable?

I tried using iptables to block request other than certain IP addresses, but still didn't work out for my setup.

I would actually prefer qtlua within torch to display things. but unfortunately it's still broken (CMIIW).

**Comment by clementfarabet** [comment]
In the server [config](https://github.com/clementfarabet/gfx.js/blob/master/server.js#L14), setting `hostname: "localhost"` will only listen to localhost connections (that's safe). I think it's the default but one should check, not sure at all. Setting `hostname: "0.0.0.0"` will listen to all available interfaces, and that's dangerous.

**Comment by andi4000** [comment]
I started gfx.js with default settings, and I can access my server from any pc within the network. The scary thing is, my server's IP address is public.

What's the rationale behind giving shell access within the page?

-- added --
`hostname: 'localhost'` in the server.js file is not the default setting, had to add it manually.

-- added --
how to completely disable terminal on the web page? other than removing the `<button>` html tag of course.
