### ISSUE TITLE
Couldn't find a suitable web browser

### ISSUE THREAD

**Issue by laotao** [clementfarabet/gfx.js#36]
Hi,
I installed torch and gfx on a remote server (with no gui) through ssh. Then I started gfx and run th -lgfx.go. Below is what I got:

[gfx.js] server already running on port 8000, graphics will be rendered into http://localhost:8000
Couldn't find a suitable web browser!
Set the BROWSER environment variable to your desired browser.
xdg-open: no method available for opening 'http://localhost:8000'

And when I accessed gfx from a windows machine and run the following lines, nothing was shown on the gfx page.

> i = image.lena()
> gfx.image(i)

Would anyone please help?

Thanks
Tao

**Comment by laotao** [comment]
I tried gfx.image() several times and it appears in the remote browser sometimes. It seems that gxf is just unstable.

**Comment by szym** [comment]
gfx.go starts the server AND opens up a browser. To just start the server run th -lgfx.start
